In [2]:
# numpy exercise 1~20

In [3]:
import numpy as np

In [4]:
print(np.__version__)

1.16.5


In [6]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
print("%d bytes" % (z.size*z.itemsize))

80 bytes


In [8]:
print(z.size)
print(z.itemsize)

10
8


In [9]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [14]:
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [15]:
z[::-2]

array([49, 47, 45, 43, 41, 39, 37, 35, 33, 31, 29, 27, 25, 23, 21, 19, 17,
       15, 13, 11])

In [16]:
z[::2]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [17]:
z = np.arange(0,9)
z.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
z = [1, 2, 0, 0, 4, 0]
z1 = np.nonzero(z)
print(z1)

(array([0, 1, 4], dtype=int64),)


In [22]:
z = np.eye(3,3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
z1 = np.random.random((3,3))
z2 = np.random.random((3,3,3))

print(z1)
print(z2)

[[0.52970037 0.99408067 0.26589347]
 [0.70076139 0.19075178 0.08715669]
 [0.44625272 0.68725746 0.58989645]]
[[[0.35303434 0.73095789 0.76588771]
  [0.86747663 0.3843893  0.62667013]
  [0.25268178 0.28449537 0.74939268]]

 [[0.03405521 0.38646722 0.62989264]
  [0.19055207 0.06614281 0.05790811]
  [0.39386104 0.44799603 0.04991653]]

 [[0.76850322 0.90257708 0.26362058]
  [0.12838939 0.39568116 0.08792314]
  [0.91220859 0.25762149 0.62223261]]]


In [25]:
z = np.random.random((10,10))
print(z)
print("Z max:", z.max(), "Z min:", z.min())


[[0.39766146 0.99029548 0.79116214 0.40503212 0.59046035 0.93925348
  0.14375129 0.17189761 0.61225831 0.71594749]
 [0.53795727 0.74190559 0.49076873 0.28402782 0.90909077 0.79557738
  0.44816814 0.49705092 0.5387656  0.99911948]
 [0.86796738 0.22660336 0.18927614 0.35805163 0.45748243 0.29396598
  0.1855346  0.8495318  0.44197679 0.54501394]
 [0.24741958 0.96508536 0.17062033 0.31756864 0.35047957 0.90622228
  0.73905638 0.62493919 0.59338664 0.06708418]
 [0.47424728 0.06613333 0.65354384 0.11517626 0.43609791 0.88507171
  0.06692426 0.82963323 0.86079033 0.79783986]
 [0.83641791 0.58567767 0.02242792 0.83631496 0.68199948 0.77959948
  0.41031673 0.14115172 0.34710235 0.27180159]
 [0.87526867 0.35114951 0.29164201 0.07347489 0.39280166 0.41618897
  0.02860945 0.56189286 0.24476475 0.25130159]
 [0.10235826 0.70117299 0.22428699 0.40569434 0.3977395  0.72124803
  0.7399349  0.44874185 0.92416987 0.07917482]
 [0.36760533 0.60563174 0.5504855  0.85930171 0.18295331 0.4699239
  0.0825355  

In [27]:
z = np.random.random(30)
print(z.mean())

0.5077360203608753


In [28]:
z = np.ones((10,10))
z[1:-1, 1:-1]=0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [30]:
z = np.ones((5,5))
z = np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [36]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
# 부동소수점 오차로 같지 않음
print(0.3 == 3 * 0.1) 

nan
False
False
nan
True
False


In [39]:
z = np.diag(np.arange(5))
print(z)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


In [44]:
z = np.diag(np.arange(4)+1, k=-2)
print(z)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]]


In [51]:
z = np.zeros((8,8))
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [52]:
z = np.unravel_index(100,(6,7,8))
print(z)

(1, 5, 4)
